# Generated by Django 4.2 on 2023-04-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default=True, max_length=40),
            preserve_default=False,
        ),
    ]
