# Generated by Django 4.2 on 2023-04-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
